<?php
require __DIR__ . "/../phpLogics/auth.php";
include(__DIR__ . "/../database/db.php");
include __DIR__ . "/../phpLogics/site_config.php";

require_role('registrar');

require_once __DIR__ . '/../phpLogics/mailer.php';
require_once __DIR__ . '/../phpLogics/certificate.php';
require_once __DIR__ . '/../phpLogics/audit.php';

/* ── Email the student when a request status changes ────────────────
 * Uses the shared mail API (phpLogics/mailer.php). Fires on
 * Processing (accepted), Released, and legacy "Ready for Pickup".
 * Failures are logged server-side and never block the update. */
function notifyStudentStatus(mysqli $conn, int $req_id, string $newStatus, ?string $reason = null, ?string $cancelledBy = null): void
{
    $notifyable = ['Processing', 'Ready for Pickup', 'Released'];
    $isRejected = ($newStatus === 'Cancelled' && $cancelledBy === 'registrar');
    if (!in_array($newStatus, $notifyable, true) && !$isRejected) {
        return;
    }

    $q = $conn->prepare(
        "SELECT s.email, s.first_name, s.last_name, dr.document_type
         FROM document_requests dr
         JOIN users s ON dr.user_id = s.id
         WHERE dr.id = ?"
    );
    $q->bind_param("i", $req_id);
    $q->execute();
    $info = $q->get_result()->fetch_assoc();
    $q->close();

    if (!$info || empty($info['email'])) {
        return;
    }

    $fullName = trim(($info['first_name'] ?? '') . ' ' . ($info['last_name'] ?? ''));
    $reqNo    = 'REQ-' . str_pad((string) $req_id, 4, '0', STR_PAD_LEFT);
    $mailStatus = $isRejected ? 'Rejected' : $newStatus;

    $result = send_status_email(
        $info['email'],
        $fullName,
        $reqNo,
        $info['document_type'] ?? 'your document',
        $mailStatus,
        $reason
    );

    if (!$result['ok']) {
        error_log("Status mail failed for {$reqNo} ({$newStatus}): " . $result['error']);
    }
}

/* ── Handle release — system-generated e-certificate ────────────────
 * The certificate PDF is GENERATED by the system from the student's
 * record; the registrar only edits the content (title/body/officer/
 * date/remarks) in the release modal. The generated PDF is saved to
 * the record and emailed to the student as an attachment. */
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['release_request'])) {
    if (!verifyCsrfToken()) {
        header("Location: registrarMainPage.php?error=csrf_fail");
        exit();
    }

    $req_id = (int)$_POST['req_id'];
    $row    = certificate_fetch($conn, $req_id);

    if (!$row) {
        header("Location: registrarMainPage.php?release_error=" . urlencode('Request not found.'));
        exit();
    }

    // ── Registrar edits (fall back to system defaults when empty) ──
    $edits = [
        'title'         => trim((string)($_POST['cert_title']    ?? '')),
        'body'          => trim((string)($_POST['cert_body']     ?? '')),
        'officer_name'  => trim((string)($_POST['officer_name']  ?? '')),
        'officer_title' => trim((string)($_POST['officer_title'] ?? '')),
        'cert_date'     => trim((string)($_POST['cert_date']     ?? '')),
        'remarks'       => trim((string)($_POST['remarks']       ?? '')),
    ];

    // Signing-officer default: the registrar currently logged in
    $q = $conn->prepare("SELECT first_name, last_name FROM users WHERE id = ?");
    $q->bind_param("i", $_SESSION['user_id']);
    $q->execute();
    $me = $q->get_result()->fetch_assoc();
    $q->close();
    $regNameDefault = $me ? trim($me['first_name'] . ' ' . $me['last_name']) : '';
    $certData = certificate_build_data($row, $edits, $regNameDefault);

    try {
        $pdf = generate_certificate_pdf($certData);
    } catch (Throwable $e) {
        error_log("Certificate generation failed (REQ-{$req_id}): " . $e->getMessage());
        header("Location: registrarMainPage.php?release_error=" . urlencode('Certificate generation failed. Please try again.'));
        exit();
    }

    // ── Save the generated PDF ──
    $uploads_fs  = dirname(__DIR__) . '/uploads';
    $dir         = $uploads_fs . '/e_certificates/';
    if (!is_dir($dir)) mkdir($dir, 0755, true);

    $filename = 'cert_' . $req_id . '_' . time() . '_' . rand(100, 999) . '.pdf';
    if (file_put_contents($dir . $filename, $pdf) === false) {
        header("Location: registrarMainPage.php?release_error=" . urlencode('Failed to save the certificate file. Please try again.'));
        exit();
    }

    // Replace: remove the previous certificate file if any
    if (!empty($row['e_certificate'])) {
        $old = $uploads_fs . '/' . ltrim($row['e_certificate'], '/');
        if (file_exists($old)) unlink($old);
    }

    $certWeb = 'uploads/e_certificates/' . $filename;

    $upd = $conn->prepare(
        "UPDATE document_requests
         SET status = 'Released', cancelled_by = NULL,
             date_released = NOW(), e_certificate = ?
         WHERE id = ?"
    );
    $upd->bind_param("si", $certWeb, $req_id);
    $upd->execute();
    $upd->close();

    // ── Email the certificate to the student ──
    $email = $fullName = null;
    $q = $conn->prepare("SELECT email, first_name, last_name FROM users WHERE id = ?");
    $q->bind_param("i", $row['student_pk']);
    $q->execute();
    $stu = $q->get_result()->fetch_assoc();
    $q->close();

    if ($stu && !empty($stu['email'])) {
        $fullName = trim($stu['first_name'] . ' ' . $stu['last_name']);
        $reqNo    = $certData['req_no'];
        $result   = send_certificate_email($stu['email'], $fullName, $reqNo, $row['document_type'], $certWeb);
        if (!$result['ok']) {
            error_log("Release mail failed for {$reqNo}: " . $result['error']);
        }
    } else {
        error_log("Release mail skipped (no email on file) for REQ-{$req_id}.");
    }

    // ── Audit: registrar released the document with a system e-cert ──
    audit_log($conn, 'CERTIFICATE_RELEASED', 'document_request', $certData['req_no'],
        "{$row['document_type']} — e-certificate generated"
        . (($stu && !empty($stu['email'])) ? " and emailed to {$stu['email']}" : ' (no email on file — NOT emailed)'));

    header("Location: registrarMainPage.php?released=1");
    exit();
}

// ── Handle status update ───────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['update_status'])) {
    // ── CSRF check ──
    if (!verifyCsrfToken()) {
        header("Location: registrarMainPage.php?error=csrf_fail");
        exit();
    }

    $req_id    = (int)$_POST['req_id'];
    $newStatus = $_POST['new_status'];
    // Simplified flow: Pending → Processing → Released, plus Cancelled (reject).
    // Legacy values ("Ready for Pickup", "Unclaimed") stay accepted so old
    // rows can still be re-saved without silently failing.
    $allowed   = ['Pending', 'Processing', 'Ready for Pickup', 'Released', 'Unclaimed', 'Cancelled'];

    if (in_array($newStatus, $allowed, true)) {
        $dbStatus    = $newStatus;
        $cancelledBy = null;

        // ── Audit: remember the current status for the change log ──
        $old = $conn->prepare("SELECT status FROM document_requests WHERE id = ?");
        $old->bind_param("i", $req_id);
        $old->execute();
        $oldStatus = (string)($old->get_result()->fetch_row()[0] ?? '?');
        $old->close();

        if ($newStatus === 'Unclaimed') {
            // Store as Cancelled with cancelled_by = 'unclaimed'
            $dbStatus    = 'Cancelled';
            $cancelledBy = 'unclaimed';
        } elseif ($newStatus === 'Cancelled') {
            // Registrar rejection — flagged so students cannot restore it.
            // A written reason is REQUIRED so the student knows why.
            $cancelledBy  = 'registrar';
            $rejectReason = trim((string)($_POST['reject_reason'] ?? ''));
            if ($rejectReason === '') {
                header("Location: registrarMainPage.php?error=reason_required");
                exit();
            }
        } else {
            $rejectReason = null;
        }

        $upd = $conn->prepare(
            "UPDATE document_requests
             SET status        = ?,
                 cancelled_by  = CASE
                                    WHEN ? = 'Cancelled' THEN ?
                                    WHEN ? IN ('Released','Pending') THEN NULL
                                    ELSE cancelled_by
                                 END,
                 rejection_reason = CASE
                                    WHEN ? = 'Cancelled' THEN ?
                                    ELSE NULL
                                 END,
                 date_released = CASE
                                    WHEN ? = 'Released' THEN NOW()
                                    WHEN ? = 'Pending'  THEN NULL
                                    ELSE date_released
                                 END
             WHERE id = ?"
        );
        $upd->bind_param("ssssssssi", $dbStatus, $dbStatus, $cancelledBy, $dbStatus, $dbStatus, $rejectReason, $dbStatus, $dbStatus, $req_id);
        $upd->execute();

        // ── Audit: registrar changed the request status ──
        if ($upd->affected_rows > 0) {
            audit_log($conn, 'STATUS_CHANGED', 'document_request',
                'REQ-' . str_pad((string) $req_id, 4, '0', STR_PAD_LEFT),
                "{$oldStatus} → {$dbStatus}"
                . ($cancelledBy !== null ? " (cancelled_by: {$cancelledBy})" : '')
                . (!empty($rejectReason) ? " — Reason: {$rejectReason}" : ''));
        }
        $upd->close();

        // 📧 Notify the student when the request reaches a key status
        notifyStudentStatus($conn, $req_id, $newStatus, $rejectReason ?? null, $cancelledBy);
    }
    header("Location: registrarMainPage.php");
    exit();
}

// ── Stats ──────────────────────────────────────────────────────────────────
$today = date('Y-m-d');

function countWhere($conn, $where, $types = '', $params = [])
{
    $n  = 0;
    $st = $conn->prepare("SELECT COUNT(*) FROM document_requests WHERE $where");
    if (!$st) return 0;
    if ($types) $st->bind_param($types, ...$params);
    $st->execute();
    $st->bind_result($n);
    $st->fetch();
    $st->close();
    return $n;
}

$cntPending    = countWhere($conn, "status = 'Pending'");
$cntProcessing = countWhere($conn, "status = 'Processing'");
$cntReleased   = countWhere($conn, "status = 'Released'");
$cntToday      = countWhere($conn, "DATE(date_requested) = ?", "s", [$today]);
$cntRejected   = countWhere($conn, "status = 'Cancelled' AND cancelled_by = 'registrar'");

// ── Dashboard: recent requests (latest 6, any status) ────────────────────
$recentReq = $conn->prepare(
    "SELECT dr.id, dr.document_type, dr.status, dr.cancelled_by, dr.date_requested,
            CONCAT(s.first_name,' ',s.last_name) AS student_name
     FROM document_requests dr JOIN users s ON dr.user_id = s.id
     ORDER BY dr.date_requested DESC, dr.id DESC LIMIT 6"
);
$recentReq->execute();
$recentRequests = $recentReq->get_result()->fetch_all(MYSQLI_ASSOC);
$recentReq->close();

// Friendly greeting by time of day (matches the Manila/MySQL clock)
$hourNow  = (int)date('G');
$greeting = $hourNow < 12 ? 'Good morning' : ($hourNow < 17 ? 'Good afternoon' : 'Good evening');

// ── Fetch registrar info for header ───────────────────────────────
$reg = $conn->prepare("SELECT * FROM users WHERE id = ?");
$reg->bind_param("i", $_SESSION['user_id']);
$reg->execute();
$registrar   = $reg->get_result()->fetch_assoc();
$reg->close();

$regName     = $registrar ? htmlspecialchars($registrar['first_name'] . ' ' . $registrar['last_name']) : 'Registrar';
$regPhoto    = !empty($registrar['profile_photo']) ? $registrar['profile_photo'] : null;
$firstName   = $registrar ? trim($registrar['first_name']) : 'Registrar';
$regInitials = $registrar
    ? strtoupper(substr($registrar['first_name'], 0, 1) . substr($registrar['last_name'], 0, 1))
    : 'R';

// ── Fetch active rows ─────────────────────────────────────────────
$mainRows = $conn->query(
    "SELECT dr.*, CONCAT(s.first_name,' ',s.last_name) AS student_name, s.profile_photo
     FROM document_requests dr
     JOIN users s ON dr.user_id = s.id
     WHERE dr.status NOT IN ('Released','Cancelled')
     ORDER BY dr.date_requested DESC"
)->fetch_all(MYSQLI_ASSOC);

// ── Fetch archived rows ───────────────────────────────────────────
// Released + ALL cancelled rows (registrar-rejected, unclaimed, and
// student-cancelled) — the registrar always sees the full picture.
$archivedRows = $conn->query(
    "SELECT dr.*, CONCAT(s.first_name,' ',s.last_name) AS student_name, s.profile_photo
     FROM document_requests dr
     JOIN users s ON dr.user_id = s.id
     WHERE dr.status IN ('Released','Cancelled')
     ORDER BY dr.date_requested DESC"
)->fetch_all(MYSQLI_ASSOC);

// ── Repeat-request map: req id => earlier requests of the SAME document
//    type by the SAME student (any status). Lets the registrar see at a
//    glance when a document has been requested before. ────────────────
$repeatMap = [];
$rep = $conn->query(
    "SELECT dr.id,
            (SELECT COUNT(*) FROM document_requests d2
             WHERE d2.user_id = dr.user_id
               AND d2.document_type = dr.document_type
               AND d2.date_requested < dr.date_requested) AS earlier_count
     FROM document_requests dr"
);
while ($row = $rep->fetch_assoc()) {
    $repeatMap[(int)$row['id']] = (int)$row['earlier_count'];
}

// ── Helpers ───────────────────────────────────────────────────────
function statusBadge($status, $cancelledBy = '')
{
    if ($status === 'Cancelled') {
        return match ($cancelledBy) {
            'registrar' => "<span class=\"status rejected\">Rejected</span>",
            'unclaimed' => "<span class=\"status unclaimed\">Unclaimed</span>",
            default     => "<span class=\"status cancelled\">Cancelled</span>",   // by student
        };
    }
    $cls = match ($status) {
        'Pending'          => 'pending',
        'Processing'       => 'processing',
        'Ready for Pickup' => 'ready',
        'Released'         => 'released',
        default            => 'pending',
    };
    return "<span class=\"status {$cls}\">{$status}</span>";
}

function avatarHtml($r)
{
    if (!empty($r['profile_photo'])) {
        // DB stores web-root-relative paths ("uploads/..."); prefix for this page's depth
        $src = '../' . htmlspecialchars($r['profile_photo']);
        return "<img src=\"{$src}\" alt=\"avatar\" class=\"avatar-img\">";
    }
    $parts    = explode(' ', trim($r['student_name']));
    $initials = strtoupper(substr($parts[0] ?? '', 0, 1) . substr($parts[1] ?? '', 0, 1));
    return "<span class=\"avatar-fallback\">{$initials}</span>";
}

function renderRow($r, $isArchived = false)
{
    global $repeatMap; // built outside — needed for the 🔁 repeat badge

    $tok     = htmlspecialchars(csrf_token(), ENT_QUOTES);
    $id      = (int)$r['id'];
    $padId   = '#' . str_pad($id, 4, '0', STR_PAD_LEFT);
    $name    = htmlspecialchars($r['student_name']);
    $doc     = htmlspecialchars($r['document_type']);
    $purpose = htmlspecialchars($r['purpose'] ?? '—');
    $dateReq = date('m/d/Y', strtotime($r['date_requested']));
    $dateRel = !empty($r['date_released']) ? date('m/d/Y', strtotime($r['date_released'])) : '—';
    $badge   = statusBadge($r['status'], $r['cancelled_by'] ?? '');
    $cur     = $r['status'];
    $avatar  = avatarHtml($r);

    // 🔁 Badge when this student already requested this document before
    $earlier = $repeatMap[$id] ?? 0;
    $repeatBadge = $earlier > 0
        ? " <span class=\"repeat-badge\" title=\"Requested this document {$earlier} time(s) before\">🔁 Repeat</span>"
        : '';

    $hasIdPhoto    = !empty($r['id_photo']);
    $idPhotoAttr    = $hasIdPhoto    ? htmlspecialchars($r['id_photo'],    ENT_QUOTES) : '';
    $eCertAttr      = !empty($r['e_certificate']) ? htmlspecialchars($r['e_certificate'], ENT_QUOTES) : '';

    $viewBtn = "<button type='button' class='btn-view-files'
                    data-req-id=\"{$id}\"
                    data-id-photo=\"{$idPhotoAttr}\"
                    data-e-cert=\"{$eCertAttr}\"
                    data-purpose=\"{$purpose}\"
                    data-student=\"{$name}\"
                    data-doc=\"{$doc}\"
                    data-date=\"" . htmlspecialchars(date('M d, Y', strtotime($r['date_requested'])), ENT_QUOTES) . "\"
                    data-status=\"" . htmlspecialchars($r['status'], ENT_QUOTES) . "\"
                    data-cancelled=\"" . htmlspecialchars($r['cancelled_by'] ?? '', ENT_QUOTES) . "\"
                    data-avatar=\"" . htmlspecialchars($r['profile_photo'] ?? '', ENT_QUOTES) . "\">
                    📎 View Details
                </button>";

    if ($isArchived) {
        $cancelledBy   = $r['cancelled_by'] ?? '';

        // Chip-filter value for this archived row
        $archStatus = 'Released';
        if ($r['status'] === 'Cancelled') {
            $archStatus = match ($cancelledBy) {
                'registrar' => 'Rejected',
                'unclaimed' => 'Unclaimed',
                default     => 'Cancelled',   // cancelled by the student
            };
        }

        return "
        <tr data-status=\"{$archStatus}\">
            <td><strong>{$padId}</strong></td>
            <td><div class='student-cell'>{$avatar}<span>{$name}</span></div></td>
            <td>{$doc}{$repeatBadge}</td>
            <td>{$dateReq}</td>
            <td>{$dateRel}</td>
            <td>{$badge}</td>

            <td><div class='action-group'>{$viewBtn}</div></td>
        </tr>";
    }

    if ($cur === 'Pending') {
        $acceptBtn = "
            <form method='POST' style='display:inline;'>
                <input type='hidden' name='csrf_token' value='{$tok}'>
                <input type='hidden' name='update_status' value='1'>
                <input type='hidden' name='req_id' value='{$id}'>
                <input type='hidden' name='new_status' value='Processing'>
                <button type='submit' class='btn-accept'
                        onclick=\"return confirm('Accept this request?')\">✔ Accept</button>
            </form>";
        $rejectBtn = "<button type='button' class='btn-reject'
                        onclick=\"openRejectModal('{$id}')\">✖ Reject</button>";
        $actions = "<div class='action-group'>{$viewBtn}{$acceptBtn}{$rejectBtn}</div>";
    } else {
        /* Simplified status flow:
           • Pending     — default
           • Processing  — set by the system when accepted
           • Released    — use when the certificate is ready
           • Reject / Cancel
        */
        $dropdownStatuses = ['Pending', 'Processing', 'Released', 'Cancelled'];

        $opts = '';
        foreach ($dropdownStatuses as $opt) {
            $sel   = ($opt === $cur) ? 'selected' : '';
            $label = ($opt === 'Cancelled') ? 'Reject / Cancel' : $opt;
            $opts .= "<option value=\"{$opt}\" {$sel}>{$label}</option>";
        }

        // Legacy rows (e.g. old "Ready for Pickup"): keep the current value
        // visible so the row renders correctly; once changed, the legacy
        // option disappears for good.
        if (!in_array($cur, $dropdownStatuses, true)) {
            $opts = "<option value=\"{$cur}\" selected>{$cur} (current)</option>{$opts}";
        }
        $statusForm = "
            <form method='POST' style='display:inline;'>
                <input type='hidden' name='csrf_token' value='{$tok}'>
                <input type='hidden' name='update_status' value='1'>
                <input type='hidden' name='req_id' value='{$id}'>
                <select name='new_status' onchange='if(this.value===\"Cancelled\" ){this.form.reset();openRejectModal(\"{$id}\");}else{this.form.submit()}' class='status-select'>
                    {$opts}
                </select>
            </form>";
        // 📤 Release — system generates the e-certificate (editable in the modal)
        $relBtn = "<button type='button' class='btn-release'
                        data-req-id=\"{$id}\"
                        data-student=\"{$name}\"
                        data-doc=\"{$doc}\"
                        title=\"Release with a system-generated e-certificate\">
                        📤 Release
                    </button>";
        $actions = "<div class='action-group'>{$viewBtn}{$relBtn}{$statusForm}</div>";
    }

    return "
    <tr data-status=\"{$cur}\">
        <td><strong>{$padId}</strong></td>
        <td><div class='student-cell'>{$avatar}<span>{$name}</span></div></td>
        <td>{$doc}{$repeatBadge}</td>
        <td>{$dateReq}</td>
        <td>{$badge}</td>

        <td>{$actions}</td>
    </tr>";
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar Dashboard — HEHMS</title>
    <link rel="stylesheet" href="registrarCSS.css">
    <link rel="stylesheet" href="accountInfo.css">
    <link rel="stylesheet" href="../assets/css/scroll-table.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">
    <?php echo theme_head(); // admin-managed brand color ?>

</head>

<body>

    <!-- ══ HEADER ══ -->
    <div class="header">
        <div class="header-left">
            <img src="<?php echo site_logo_url(); ?>" alt="School Logo" class="logo-img">
            <div class="school-info">
                <h2>Hilario E. Hermosa Memorial High School</h2>
                <p>Siclong Laur, Nueva Ecija</p>
            </div>
        </div>
        <div class="header-right">

            <a href="../phpLogics/Logout.php" class="logout-btn">↪ Logout</a>
        </div>
    </div>

    <div class="body-layout">

        <!-- ══ SIDEBAR ══ -->
        <aside class="sidebar">
            <div class="sidebar-brand">
                <p>Logged as</p>
                <h3><?php echo $regName; ?></h3>
            </div>
            <nav class="sidebar-nav">
                <div class="nav-group-label">Main</div>
                <a href="registrarMainPage.php" class="nav-main-item dashboard active" id="nav-dash" onclick="switchView('dashboard'); return false;">
                    <div class="nmi-icon">🏠</div>
                    <div class="nmi-text">
                        <div class="nmi-title">Dashboard</div>
                        <div class="nmi-sub">Overview &amp; activity</div>
                    </div>
                </a>

                <a href="registrarMainPage.php" class="nav-main-item requests" id="nav-req" onclick="switchView('main'); return false;">
                    <div class="nmi-icon">📋</div>
                    <div class="nmi-text">
                        <div class="nmi-title">Student Requests</div>
                        <div class="nmi-sub">Accept &amp; verify requests</div>
                    </div>
                </a>

                <a href="registrarMainPage.php?view=account" class="nav-main-item records" id="nav-acc" onclick="switchView('account'); return false;">
                    <div class="nmi-icon">👤</div>
                    <div class="nmi-text">
                        <div class="nmi-title">Account Information</div>
                        <div class="nmi-sub">Update your profile</div>
                    </div>
                </a>

                <div class="nav-divider"></div>
                <div class="nav-group-label">Tools</div>

                <a href="../phpLogics/Logout.php" class="nav-link"><span class="nl-icon">↪</span> Logout</a>
            </nav>
        </aside>

        <!-- ══ MAIN ══ -->
        <div class="main-container">
            <div class="title-section" id="shared-title">
                <h1>Registrar <span>Dashboard</span></h1>
                <p>Manage student document requests and records.</p>
            </div>

            <!-- CSRF failure notice (status update was NOT performed) -->
            <?php if (isset($_GET['error']) && $_GET['error'] === 'csrf_fail'): ?>
                <div class="alert-banner">⚠️ Your session expired — the last action was not performed. Please try again.</div>
            <?php endif; ?>

            <?php if (isset($_GET['released'])): ?>
                <div class="alert-banner success">✔ Request released — the student has been notified by email.</div>
            <?php endif; ?>

            <?php if (isset($_GET['release_error'])): ?>
                <div class="alert-banner">⚠️ <?php echo htmlspecialchars($_GET['release_error']); ?></div>
            <?php endif; ?>

            <!-- ══════ VIEW: DASHBOARD (landing) ══════ -->
            <div id="view-dashboard">

                <!-- Welcome banner -->
                <div class="dash-welcome">
                    <div class="dash-welcome-text">
                        <h2><?php echo $greeting; ?>, <?php echo htmlspecialchars($firstName); ?>! 👋</h2>
                        <p><?php echo date('l, F j, Y'); ?> · Registrar's Office · Hilario E. Hermosa Memorial High School</p>
                    </div>
                    <div class="dash-welcome-actions">
                        <a class="btn-export" href="../phpLogics/exportReport.php" target="_blank" title="Printable monthly report (PDF)">🧾 Report PDF</a>
                    </div>
                </div>

                <!-- Stat cards (clickable — jump to the filtered table) -->
                <div class="cards">
                    <div class="card card-click" data-goto="Pending" title="Show pending requests">
                        <span class="card-icon">⏳</span>
                        <h4>Pending Requests</h4>
                        <h2><?php echo $cntPending; ?></h2>
                    </div>
                    <div class="card card-click" data-goto="Processing" title="Show processing requests">
                        <span class="card-icon">⚙️</span>
                        <h4>Processing</h4>
                        <h2><?php echo $cntProcessing; ?></h2>
                    </div>
                    <div class="card card-click" data-goto="Released" data-view="archived" title="Show released requests">
                        <span class="card-icon">✅</span>
                        <h4>Released</h4>
                        <h2><?php echo $cntReleased; ?></h2>
                    </div>
                    <div class="card card-click" data-goto="Rejected" data-view="archived" title="Show rejected requests">
                        <span class="card-icon">🚫</span>
                        <h4>Rejected</h4>
                        <h2><?php echo $cntRejected; ?></h2>
                    </div>
                    <div class="card card-click" title="Show today's requests">
                        <span class="card-icon">📅</span>
                        <h4>Today's Requests</h4>
                        <h2><?php echo $cntToday; ?></h2>
                    </div>
                </div>

                <!-- Recent requests -->
                <div class="dash-grid">
                    <div class="dash-panel">
                        <div class="dash-panel-head">
                            <h3>🗂️ Recent Requests</h3>
                            <button type="button" class="btn-export" onclick="switchView('main')">View all →</button>
                        </div>
                        <div class="dash-recent-list">
                            <?php if (empty($recentRequests)): ?>
                                <p class="dash-empty">No requests yet.</p>
                            <?php else: foreach ($recentRequests as $r):
                                $badge = statusBadge($r['status'], $r['cancelled_by'] ?? '');
                            ?>
                                <div class="dash-recent-item">
                                    <div class="dash-ri-main">
                                        <strong>REQ-<?php echo str_pad((string)$r['id'], 4, '0', STR_PAD_LEFT); ?></strong>
                                        <span class="dash-ri-doc"><?php echo htmlspecialchars($r['document_type']); ?></span>
                                    </div>
                                    <div class="dash-ri-side">
                                        <span class="dash-ri-name"><?php echo htmlspecialchars($r['student_name']); ?></span>
                                        <div>
                                            <?php echo $badge; ?>
                                            <small class="dash-ri-date"><?php echo date('M d, g:i A', strtotime($r['date_requested'])); ?></small>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; endif; ?>
                        </div>
                    </div>

                    
                </div>
            </div>

            <!-- ══════ VIEW: REQUESTS ══════ -->
            <div id="view-requests" style="display:none;">

            <!-- Tab switcher -->
            <div class="switch-btn">
                <a class="active" id="tab-main">Main</a>
                <a id="tab-archived">History</a>
            </div>

            <!-- Active requests -->
            <div class="container" id="view-main">
                <div class="table-header">
                    <h3>Active Requests</h3>
                    <div class="table-header-controls">
                        <div class="search-wrapper">
                            <span class="search-icon">🔍</span>
                            <input type="text" class="search" id="search-main" placeholder="Search requests...">
                        </div>
                        <a class="btn-export" href="../phpLogics/exportReport.php"
                            title="Printable monthly summary report (PDF)" target="_blank">🧾 Report PDF</a>
                    </div>
                </div>

                <!-- Status filter chips -->
                <div class="filter-chips" id="chips-main">
                    <button type="button" class="chip active" data-filter="">All</button>
                    <button type="button" class="chip" data-filter="Pending">⏳ Pending</button>
                    <button type="button" class="chip" data-filter="Processing">⚙️ Processing</button>
                </div>
                <div class="tbl-scroll-wrap">
                <table class="tbl-x" style="min-width: 1000px;">
                    <thead>
                        <tr>
                            <th>Req ID</th>
                            <th>Student Name</th>
                            <th>Document</th>
                            <th>Date Requested</th>
                            <th>Status</th>

                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody id="main-tbody">
                        <?php if (empty($mainRows)): ?>
                            <tr>
                                <td colspan="6" class="empty-row">📭 No active requests.</td>
                            </tr>
                        <?php else: foreach ($mainRows as $r) echo renderRow($r, false);
                        endif; ?>
                    </tbody>
                </table>
                </div>
            </div>

            <!-- Request history (released / cancelled) -->
            <div class="container" id="view-archived" style="display:none;">
                <div class="table-header">
                    <h3>Request History</h3>
                    <div class="table-header-controls">
                        <div class="search-wrapper">
                            <span class="search-icon">🔍</span>
                            <input type="text" class="search" id="search-archived" placeholder="Search history...">
                        </div>
                    </div>
                </div>

                <!-- Status filter chips -->
                <div class="filter-chips" id="chips-archived">
                    <button type="button" class="chip active" data-filter="">All</button>
                    <button type="button" class="chip" data-filter="Released">✔ Released</button>
                    <button type="button" class="chip" data-filter="Rejected">🚫 Rejected</button>
                    <button type="button" class="chip" data-filter="Cancelled">✖ Cancelled</button>
                </div>
                <div class="tbl-scroll-wrap">
                <table class="tbl-x" style="min-width: 1080px;">
                    <thead>
                        <tr>
                            <th>Req ID</th>
                            <th>Student Name</th>
                            <th>Document</th>
                            <th>Date Requested</th>
                            <th>Date Released</th>
                            <th>Status</th>

                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody id="archived-tbody">
                        <?php if (empty($archivedRows)): ?>
                            <tr>
                                <td colspan="7" class="empty-row">📭 No request history yet.</td>
                            </tr>
                        <?php else: foreach ($archivedRows as $r) echo renderRow($r, true);
                        endif; ?>
                    </tbody>
                </table>
                </div>
            </div>
            </div><!-- /view-requests -->

            <!-- ══════ VIEW: ACCOUNT INFORMATION ══════ -->
            <div id="view-account" style="display:none;">
                <div class="title-section">
                    <h1>Account <span>Information</span></h1>
                    <p>View and update your own registrar profile.</p>
                </div>

                <div class="account-card">
                    <div class="avatar-section">
                        <div class="account-avatar" id="avatar-display">
                            <?php if ($regPhoto): ?>
                                <img src="<?php echo htmlspecialchars('../' . $registrar['profile_photo']); ?>" alt="avatar">
                            <?php else: ?>
                                <span><?php echo $regInitials; ?></span>
                            <?php endif; ?>
                        </div>
                        <div>
                            <label for="photo-input" class="btn-upload">✏️ Change Photo</label>
                            <input type="file" id="photo-input" accept="image/jpeg,image/png,image/gif,image/webp" style="display:none">
                            <div id="photo-name" class="file-name"></div>
                        </div>
                    </div>

                    <div class="form-grid">
                        <div class="form-group">
                            <label>First Name <span class="req-star">*</span></label>
                            <input type="text" id="acc-first" maxlength="100" value="<?php echo htmlspecialchars($registrar['first_name'] ?? ''); ?>">
                        </div>
                        <div class="form-group">
                            <label>Last Name <span class="req-star">*</span></label>
                            <input type="text" id="acc-last" maxlength="100" value="<?php echo htmlspecialchars($registrar['last_name'] ?? ''); ?>">
                        </div>
                        <div class="form-group full">
                            <label>Email <span class="req-star">*</span></label>
                            <input type="email" id="acc-email" value="<?php echo htmlspecialchars($registrar['email'] ?? ''); ?>">
                        </div>
                        <div class="form-group full">
                            <label>Contact Number</label>
                            <input type="text" id="acc-contact" inputmode="numeric" maxlength="11"
                                value="<?php echo htmlspecialchars($registrar['contact'] ?? ''); ?>" placeholder="09XXXXXXXXX">
                        </div>
                        <div class="form-group full">
                            <label>Current Password <span class="hint-inline">(required when changing password)</span></label>
                            <input type="password" id="acc-current-password" autocomplete="current-password">
                        </div>
                        <div class="form-group full">
                            <label>New Password <span class="hint-inline">(leave blank to keep current)</span></label>
                            <input type="password" id="acc-password" autocomplete="new-password">
                        </div>
                    </div>

                    <button type="button" class="save-btn" id="btn-save-account">💾 Save Changes</button>
                </div>
            </div><!-- /view-account -->
        </div><!-- /main-container -->
    </div><!-- /body-layout -->

    <footer class="footer">
        <div class="footer-container">
            <div class="footer-center">
                <h3>&copy; 2026 Hilario E. Hermosa Memorial High School. All rights reserved.</h3>
                <p>Credential Request &amp; Tracking System</p>
            </div>
        </div>
    </footer>


    <div class="toast" id="toast"></div>

    <script>var CSRF_TOKEN = <?php echo json_encode(csrf_token()); ?>;</script>
    <script src="registrarJS.js?v=2"></script>
    <script src="../assets/js/session-timeout.js" defer></script>

    <!-- ══ Reject Reason Modal ══ -->
    <div id="reject-modal">
        <div class="reject-modal-box">
            <h3>✖ Reject Request</h3>
            <p class="reject-modal-sub">The student will see this reason in their request history. Please be specific.</p>
            <form method="POST" action="registrarMainPage.php" id="reject-form">
                <input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars(csrf_token()); ?>">
                <input type="hidden" name="update_status" value="1">
                <input type="hidden" name="new_status" value="Cancelled">
                <input type="hidden" name="req_id" id="reject-req-id" value="">
                <label for="reject-reason-input">Reason for rejection <span style="color:#b33;">*</span></label>
                <textarea id="reject-reason-input" name="reject_reason" rows="3" maxlength="500" required
                    placeholder="e.g. Incomplete requirements — please attach a valid ID"></textarea>
                <div class="reject-modal-actions">
                    <button type="button" class="btn-cancel-modal" onclick="closeRejectModal()">Cancel</button>
                    <button type="submit" class="btn-reject">✖ Reject Request</button>
                </div>
            </form>
        </div>
    </div>

    <!-- ══ Request Details Modal ══ -->
    <div id="file-modal">
        <div class="modal-box">

            <!-- Modal header -->
            <div class="modal-header">
                <div class="modal-title-wrap">
                    <span class="modal-title-icon">📋</span>
                    <div class="modal-title-text">
                        <span class="modal-title">Request Details</span>
                        <span class="modal-subtitle" id="modal-req-id">—</span>
                    </div>
                </div>
                <button class="modal-close" id="closeFileModal" type="button">✕ Close</button>
            </div>

            <!-- Scrollable body -->
            <div class="modal-scroll">

                <!-- Request summary strip -->
                <div class="modal-summary">
                    <div class="ms-cell ms-student">
                        <span class="ms-avatar" id="ms-avatar"></span>
                        <div class="ms-fields">
                            <span class="ms-label">Student</span>
                            <span class="ms-value" id="ms-student">—</span>
                        </div>
                    </div>
                    <div class="ms-cell">
                        <span class="ms-label">Document</span>
                        <span class="ms-value" id="ms-doc">—</span>
                    </div>
                    <div class="ms-cell">
                        <span class="ms-label">Date Requested</span>
                        <span class="ms-value" id="ms-date">—</span>
                    </div>
                    <div class="ms-cell">
                        <span class="ms-label">Status</span>
                        <span class="ms-value" id="ms-status-wrap">—</span>
                    </div>
                </div>

                <!-- Student information (for identity verification) -->
                <div class="modal-section">
                    <p class="modal-section-label">👤 Student Information</p>
                    <div class="student-info" id="student-info">
                        <p class="history-loading">Loading…</p>
                    </div>
                </div>

                <!-- Purpose -->
                <div class="modal-purpose-box">
                    <p class="modal-section-label">📝 Purpose / Reason</p>
                    <p id="modal-purpose">—</p>
                </div>

                <!-- Uploaded requirements -->
                <div class="modal-section">
                    <p class="modal-section-label">📎 Submitted Requirements</p>
                    <div class="docs-grid" id="docs-grid"></div>
                </div>

                <!-- History -->
                <div class="modal-section">
                    <p class="modal-section-label">🕘 Request History — This Student</p>
                    <div id="content-history" class="history-list">
                        <p class="history-loading">Loading…</p>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!-- ══ Release Modal — system-generated e-certificate ══ -->
    <div id="release-modal">
        <div class="modal-box release-box">
            <div class="modal-header">
                <div class="modal-title-wrap">
                    <span class="modal-title-icon">📤</span>
                    <div class="modal-title-text">
                        <span class="modal-title">Release with e-Certificate</span>
                        <span class="modal-subtitle" id="rel-req-id">—</span>
                    </div>
                </div>
                <button class="modal-close" id="closeReleaseModal" type="button">✕ Close</button>
            </div>

            <form method="POST" class="release-form">
                <input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars(csrf_token(), ENT_QUOTES); ?>">
                <input type="hidden" name="release_request" value="1">
                <input type="hidden" name="req_id" id="rel-req-id-input" value="">

                <div class="release-info">
                    <div><span>Student</span><strong id="rel-student">—</strong></div>
                    <div><span>Document</span><strong id="rel-doc">—</strong></div>
                </div>

                <p class="modal-section-label">✏️ Edit the system-generated certificate</p>

                <div class="release-fields">
                    <div class="rf-group">
                        <label>Certificate Title</label>
                        <input type="text" id="rf-title" name="cert_title" maxlength="120">
                    </div>
                    <div class="rf-group rf-date">
                        <label>Issue Date</label>
                        <input type="date" id="rf-date" name="cert_date">
                    </div>
                    <div class="rf-group">
                        <label>Signing Officer</label>
                        <input type="text" id="rf-officer" name="officer_name" maxlength="100">
                    </div>
                    <div class="rf-group">
                        <label>Position / Title</label>
                        <input type="text" id="rf-officer-title" name="officer_title" maxlength="100">
                    </div>
                    <div class="rf-group rf-full">
                        <label>Certificate Body
                            <span class="rf-hint">Placeholders: {NAME} {SY} {DATE} {PURPOSE} {LRN} {GRADE}</span>
                        </label>
                        <textarea id="rf-body" name="cert_body" rows="4" maxlength="1500"></textarea>
                    </div>
                    <div class="rf-group rf-full">
                        <label>Additional Remarks <span class="rf-hint">(optional)</span></label>
                        <textarea id="rf-remarks" name="remarks" rows="2" maxlength="400"></textarea>
                    </div>
                </div>

                <p class="modal-section-label">👁 Live Preview</p>
                <div class="release-preview-wrap">
                    <iframe id="rel-preview" src="about:blank" title="Certificate preview"></iframe>
                </div>
                <div class="preview-actions">
                    <button type="button" class="btn-refresh-preview" id="btn-refresh-preview">🔄 Refresh Preview</button>
                    <button type="button" class="btn-refresh-preview btn-full-preview" id="btn-fullscreen-preview"
                        title="Open the certificate full-size in a new tab">⛶ Fullscreen</button>
                </div>

                <p class="release-note">
                    On release, this certificate is <strong>generated as a PDF by the system</strong>,
                    <strong>emailed to the student as an attachment</strong>, and saved to their record
                    (downloadable in their My Requests → History).
                </p>

                <button type="submit" class="btn-release-big">✔ Mark as Released &amp; Email Certificate</button>
            </form>
        </div>
    </div>

    <!-- ══ Fullscreen Document Viewer (lightbox) ══ -->
    <div id="doc-lightbox">
        <div class="lb-bar">
            <span class="lb-caption" id="lightbox-caption"></span>
            <div class="lb-bar-actions">
                <a class="lb-btn" id="lightbox-open" href="#" target="_blank" rel="noopener">↗ Open in New Tab</a>
                <button class="lb-btn" id="lightbox-close" type="button">✕ Close</button>
            </div>
        </div>
        <div class="lb-stage">
            <img id="lightbox-img" src="" alt="Document preview">
            <iframe id="lightbox-frame" src="about:blank" title="PDF preview"></iframe>
        </div>
    </div>
</body>

</html>